CREATE TABLE AutomatyOddechowe(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(127) NOT NULL,
	Type NVARCHAR(127) NOT NULL,
	Description NVARCHAR(127) NOT NULL,
	Price DECIMAL NOT NULL,
	Photo NVARCHAR(127) NOT NULL,
	UniqueID NVARCHAR(127) NOT NULL,
);

CREATE TABLE Boje(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(127) NOT NULL,
	Type NVARCHAR(127) NOT NULL,
	Description NVARCHAR(127) NOT NULL,
	Price DECIMAL NOT NULL,
	Photo NVARCHAR(127) NOT NULL,
	UniqueID NVARCHAR(127) NOT NULL,
);

CREATE TABLE Butle(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(127) NOT NULL,
	Type NVARCHAR(127) NOT NULL,
	Description NVARCHAR(127) NOT NULL,
	Price DECIMAL NOT NULL,
	Photo NVARCHAR(127) NOT NULL,
	UniqueID NVARCHAR(127) NOT NULL,
);

CREATE TABLE Kamizelki(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(127) NOT NULL,
	Type NVARCHAR(127) NOT NULL,
	Description NVARCHAR(127) NOT NULL,
	Price DECIMAL NOT NULL,
	Photo NVARCHAR(127) NOT NULL,
	UniqueID NVARCHAR(127) NOT NULL,
);

CREATE TABLE Skafandry(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(127) NOT NULL,
	Type NVARCHAR(127) NOT NULL,
	Description NVARCHAR(127) NOT NULL,
	Price DECIMAL NOT NULL,
	Photo NVARCHAR(127) NOT NULL,
	UniqueID NVARCHAR(127) NOT NULL,
);