CREATE TABLE UserActivity(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(127) NOT NULL,
	Type NVARCHAR(127) NOT NULL,
	Description NVARCHAR(127) NOT NULL,
	Price DECIMAL NOT NULL,
	Photo NVARCHAR(127) NOT NULL,
	UniqueID NVARCHAR(127) NOT NULL,
)